#build site:
#  image: node:6
#  stage: build
#  script:
#    - npm install --progress=false
#    - npm run build
#  artifacts:
#    paths:
#      - dist

deploy:
  tags:
    - shell
  script:
    - docker build -t timetable-mosit .
    - docker run -d -p 8081:8081 --rm --name timetable-front timetable-mosit
